### ISSUE TITLE
Crashes on wake from sleep (RG35xxH)

### ISSUE THREAD

**Issue by geomusicmaker** [knulli-cfw/distribution#127]
### Knulli build version

40-dev-d3b520f949 2024/07/21 02:18

### Your architecture

RG35xx H

### Issue description

If the console goes to sleep by itself, when I wake it, it always crashes and I have to hard power-off in order to boot it again.

### Detailed reproduction steps

1. Allow console to screen timeout and go to sleep
2. Wake console (it can be responsive and begin to work)
3. Console crashes after 1-2 seconds
4. hold down power to completely power down the console.

### Details of any modifications you have made to Knulli.

No mods have been made

**Comment by Mikhailzrick** [comment]
Issue has been resolved. It would happen if entering suspend from any method besides the power button.

**Comment by andriniaina** [comment]
@Mikhailzrick  Looks like this issue is still there for rg40xxV on release 20240721. Could you link to the commit so I can debug?

**Comment by Mikhailzrick** [comment]
> @Mikhailzrick Looks like this issue is still there for rg40xxV on release 20240721. Could you link to the commit so I can debug?

Just replacing the power-button script in /usr/bin/ in the 7/21 public build with the current file from GitHub would probably fix it.

https://github.com/knulli-cfw/distribution/blob/knulli-main/board/batocera/allwinner/h700/fsoverlay/usr/bin/power-button

**Comment by andriniaina** [comment]
Indeed. Fixed! Thanks a lot
