### ISSUE TITLE
Audio coming directly from device while connected to television with HDMI

### ISSUE THREAD

**Issue by Schrau** [knulli-cfw/distribution#78]
### Knulli build version

40-dev-d8b86623f3 2024/05/30 01:50

### Your architecture

RG35XX H

### Issue description

While connected to a television via HDMI cable, the system sound still comes from the device instead of through the speakers or audio out on the television. There doesn't seem to be any system options for selecting audio output.

### Detailed reproduction steps

1: Connect device to television via HDMI mini to HDMI cable
2: Turn television on
3: Turn unit on, wait for Knulli to boot
4: Device screen is blank, correctly displays on television
5: All audio (frontend, in-game) comes from device, television outputs are silent

### Details of any modifications you have made to Knulli.

No modifications

**Comment by HoroTW** [comment]
Hi there,

This is a known issue since the 20240530 release:

> HDMI support works fine after the console boots, if you boot with HDMI connected, disconnect/connect the cable after boot

This is taken from https://github.com/knulli-cfw/distribution/releases/tag/20240530
So for now, you need to disconnect and reconnect the HDMI, then everything should work as expected...

I can see how this might not be nice for a more stationary setup.
I guess we could maybe extend the startup scripts to check for connected HDMI, but I don't know if it's a deeper issue with the video/audio card or something - I'd have to experiment with that to see if it's fixable in scripts.

Anyway, I think the report is nice so we can keep track of this issue and other people can find it easier too!

~Horo

**Comment by ChrisBeWithYou** [comment]
It'd be nice to have the option to output to both, if available!

**Comment by fedekrum** [comment]
Hi!
Same issue here, but the plug/unplug trick does not work for me.
The audio is always coming out from the device.
I am using  the latest, v. 20240721

**Comment by Mikhailzrick** [comment]
Issue has been resolved

**Comment by jeffmilton** [comment]
Having this same issue. RG40xxyh using latest build. Unplugging after boot and plugging back in didnt fix it.

**Comment by Mikhailzrick** [comment]
> Having this same issue. RG40xxyh using latest build. Unplugging after boot and plugging back in didnt fix it.

On the latest firefly release? Audio settings on auto?
